# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Y_euler_sim_cpp <- function(B, n, t, Tt, y0, r, alpha, lambda, sigmaV, rho) {
    .Call(`_HestonEMcpp_Y_euler_sim_cpp`, B, n, t, Tt, y0, r, alpha, lambda, sigmaV, rho)
}

